### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
BREAKING CHANGE: Formatting changed due to major Prettier update

I've changed Prettier's `arrowParens` to `always` as that's [the recommended way](https://prettier.io/blog/2020/03/21/2.0.0.html#change-default-value-for-arrowparens-to-always-7430httpsgithubcomprettierprettierpull7430-by-kachkaevhttpsgithubcomkachkaev) from now on.

### CODE REVIEW

**Comment by kentcdodds** [comment]
I disagree with the recommendation. I'll not be changing that config value.

**Comment by MichaelDeBoey** [comment]
I'll revert the option again 🙂

**Comment by MichaelDeBoey** [comment]
@kentcdodds Reverted the `arrowParens` option 🙂

**Pull request merged**
