### PR TITLE
BREAKING CHANGE: Use jest 27

### PR DESCRIPTION
**Pull request by eps1lon**
BREAKING CHANGE: Uses jest 27

**What**:

Use jest 27 ([migration guide](https://jestjs.io/blog/2021/05/25/jest-27))

**Why**:

- latet release
- reported bugs in testing-library/react (https://github.com/testing-library/react-testing-library/issues/918) that are easier to investigate with jest 27 as the default

**How**:

Bump releated dependencies and fix breaking changes

**Checklist**:

- [ ] Documentation
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Super 👍

**Comment by kentcdodds** [comment]
Could you configure legacy peer deps in the npmrc to deal with the typeahead issue?

**Comment by eps1lon** [comment]
> Could you configure legacy peer deps in the npmrc to deal with the typeahead issue?

Only checked their source version regarding matching `peerDependencies`. Considering `jest-watch-typeahead` only needs to cut a release, I'd wait for a day or two (https://github.com/jest-community/jest-watch-typeahead/issues/61).

**Comment by kentcdodds** [comment]
@all-contributors please add @eps1lon for code

**Comment by MichaelDeBoey** [comment]
@kentcdodds Seems like this wasn't released as a new major 🤔

**Comment by kentcdodds** [comment]
Whoops!

**Pull request merged**
