### PR TITLE
Certificate support for semantic-release

### PR DESCRIPTION
**Pull request by wejendorp**
**What**:
Adds module for semantic-release latest tag resolution.

Usage in `package.json`:
```
"release": {
	"getLastRelease": "tradeshift-scripts/last-release-npm"
},
```

**Why**:
The default handler [semantic-release/last-release-npm](https://github.com/semantic-release/last-release-npm) is not compatible with mutual TLS on internal registry.

**How**:
Uses `npm` binary directly, so all certificate info gets included.

### CODE REVIEW

**Comment by wejendorp** [comment]
oops, sorry.. wrong target.

**Comment by kentcdodds** [comment]
👋 😅

**Comment by wejendorp** [comment]
🙈 Great project btw, now that I've notified you anyway.

**Comment by kentcdodds** [comment]
I'm glad you like it @wejendorp!

**Pull request closed without merging**
