### PR TITLE
chore: update rollup to exclude es5-ext

### LINKED ISSUE #242: upgrade rollup to the latest version
The current version of your package includes an older version of rollup. This version has a package as a dependency called es5-ext which is considered malicious.  

Please consider taking a look yourself:
https://github.com/medikoo/es5-ext/issues/

### PR DESCRIPTION
**Pull request by Sembauke**
**What**:

**Why**:

**How**:

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged
      

closes #242

### CODE REVIEW

**Comment by kentcdodds** [comment]
Can you verify whether there are any breaking changes we need to address?

**Comment by kentcdodds** [comment]
CI passed, but I don't have the bandwidth to verify there were no issues outside of the automated checks and I would like someone to go through the changelog of the various tools to make sure there's nothing we need to handle. Once that's done I can merge.

**Comment by Sembauke** [comment]
Hey @kentcdodds 

Thank you for the quick response. I am not entirely sure what you are asking me to do.

But I have tested my changes locally and everything seems to build.  But the build process might be worth double checking of course!

>  I would like someone to go through the changelog of the various tools to make sure there's nothing we need to handle.

Do you want me to go through any breaking changes that might have been introduced while updating the package?

**Comment by Sembauke** [comment]
Okay I have done the following:
1. I created a new directory named "Compare"
2. I ran `npm run build` on this chore branch
3. I moved the generated `dist` folder to the compare folder 
4. I ran git checkout on the main branch and did the same step 1 through 3 but named it `dist_old`
5. Then I compared the two directories (and sub-directories) with this macOS command: `diff -qr dist dist_old`

I concluded that the directories are the same, there are no defined changes to the bundled code. If you want to double check please do. I hope this answers your doubt.

cc: @kentcdodds (Sorry for the ping)

**Review by kentcdodds — APPROVED** [review]
Thanks for putting the work into this!

**Comment by Sembauke** [comment]
Awesome, thanks for the quick response.

**Pull request merged**
