### PR TITLE
feat: upgrade to babel 7

### PR DESCRIPTION
**Pull request by alexandernanberg**
**What**:
Upgrade to babel 7

**Why**:
Get new features, bug fixes etc

**How**:
Followed the migration guide, tested and fixed some things that had broken.

Before merging this, please test this thoroughly! All tests are passing but I'm not sure that they cover all use-cases. I've tested with some of my own libraries and it seemed to work fine, although Downshift had some problems with the new macros.

**Checklist**:

- [ ] Documentation N/A
- [ ] Tests NA/
- [ ] Ready to be merged 
- [ ] Added myself to contributors table N/A

### CODE REVIEW

**Comment by kentcdodds** [comment]
Actually, it looks like downshift is experiencing issues in master right now! 😱 

https://travis-ci.org/paypal/downshift/builds/420299575

I'm fairly confident in you and your changes here so I'll go ahead and merge this. Then we should fix downshift! Thanks again!

**Comment by alexandernanberg** [comment]
Cool, although that's another error I think. I'll have a look!

**Comment by alexandernanberg** [comment]
Huh weird, travis is failing but all tests are passing locally for me 🤔

**Pull request merged**
