### PR TITLE
Update dependencies and replace uglify plugin with terser

### PR DESCRIPTION
**Pull request by alexandernanberg**
**What**:
- Update dependencies
- Replace `babel-macros` with `babel-plugin-macros`
- Replace `rollup-plugin-uglify` with `rollup-plugin-terser`
- Add `babel-core` as a dependency

If you'd like I can separate these into their own PRs

**Why**:
- Keeping stuff up-to-date
- `babel-macros` was renamed
- `uglify-es` isn't supported anymore ([and has some nasty bugs](https://twitter.com/greweb/status/1013122437884542978)). `rollup-plugin-uglify` has reverted to `uglify-js` so to keep being able to transpile es6+ we move to terser
- `rollup-plugin-babel` have `babel-core` as a `peerDependency`. Not sure if this was an intended decision to no have it as a dependency or not

**How**:
Everything was pretty much just a drop-in replacement

I did a `yarn link` to test that everything was working and Downshift had no issues that I can tell. Although I'd like you to test this before merging as well

**Checklist**:

* [ ] Documentation N/A
* [ ] Tests N/A
* [x] Ready to be merged 
* [ ] Added myself to contributors table N/A

### CODE REVIEW

**Comment by alexandernanberg** [comment]
Not sure if this should be a major release or not 🤔

**Comment by alexandernanberg** [comment]
Sure, did a rebase to fix the conflicts! 

Although I did notice that there are some new eslint errors now. This is from the Downshift codebase
image

Is this intended or something that we need to adjust?

Also, I haven't upgraded Jest yet, do you want that to be added? Looks like there are no breaking changes AFAIK

**Comment by kentcdodds** [comment]
Let's upgrade Jest.

Also, I've disabled that eslint rule in eslint-config-kentcdodds, it's kinda... useless... Other than that, yes, we'll want to update downshift to fix linting issues. Thanks!

**Comment by alexandernanberg** [comment]
Cool! I've updated the PR to also include Jest now

**Comment by kentcdodds** [comment]
Thank you @alexandernanberg!

**Pull request merged**
