### PR TITLE
fix(rollup): properly handle no externals

### PR DESCRIPTION
**Pull request by alexzherdev**
**What**:
UMD build of dom-testing-library is broken: https://github.com/kentcdodds/dom-testing-library/issues/251

**Why**:
When there are no externals, [this pattern](https://github.com/kentcdodds/kcd-scripts/commit/ad1826ec6bbb4c0c75e45471504e4951696ffded#diff-a1cfe028f2f056e2d30db017481d4ad0R90) reduces to `/^()($|\/)/` which matches any absolute path e.g. `/Users/admin/.../dom-testing-library/src/get-queries-for-element.js`

**How**:
Only match the regex when there is more than 0 externals.

**Checklist**:

- [ ] Documentation N/A
- [ ] Tests N/A
- [x] Ready to be merged

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks for this! What happens if I end up adding even one peerDependency though? I think there's more we can do here to make this smarter 🤔

**Comment by alexzherdev** [comment]
In that case the first capturing group will not be empty and the regex will no longer match any random absolute path like in my example above. I can double-check this later though.

**Comment by kentcdodds** [comment]
Ooooh, I see. That makes sense! Thanks a ton!

**Comment by kentcdodds** [comment]
@allcontributors[bot] please add @alexzherdev for code

**Pull request merged**
